In [1]:
import numpy as np
np.random.seed(1)

In [2]:
def to_onehot(UX):
    UA = np.eye(4,4)[UX]
    UA = np.delete(UA, 0, axis=1)
    return UA

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [5]:
data = np.array([[3, 0, 0, 1, 2, 3],
                [3, 0, 1, 0, 2, 1],
                [0, 2, 0, 1, 0, 0],
                [1, 0, 2, 0, 1, 0]])

In [6]:
U1 = to_onehot(data[0])
U2 = to_onehot(data[1])
U3 = to_onehot(data[2])
U4 = to_onehot(data[3])

In [7]:
Filter1 = np.random.random(size=[6,3])
Filter2 = np.random.random(size=[6,3])
Filter3 = np.random.random(size=[6,3])
Filter4 = np.random.random(size=[6,3])
Filter5 = np.random.random(size=[6,3])

In [8]:
Filter1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01]])

In [9]:
hidden_bias = np.random.random(size=5)
visual_bias = np.random.random(size=[6,3])

In [10]:
hidden_bias[0]

0.11474597295337519

In [11]:
np.sum(U1 * Filter1) + hidden_bias[0]

2.0904843466107743

In [103]:
#-------------------------

In [104]:
h1 = sigmoid(np.sum(U1 * Filter1) + hidden_bias[0])
h2 = sigmoid(np.sum(U1 * Filter2) + hidden_bias[1])
h3 = sigmoid(np.sum(U1 * Filter3) + hidden_bias[2])
h4 = sigmoid(np.sum(U1 * Filter4) + hidden_bias[3])
h5 = sigmoid(np.sum(U1 * Filter5) + hidden_bias[4])

In [105]:
hidden_layer = np.array([h1, h2, h3, h4, h5])

In [106]:
hidden_layer

array([0.94529372, 0.97000578, 0.89150664, 0.95035336, 0.97646642])

In [107]:
visual_layer = hidden_layer[0]*Filter1 + hidden_layer[1]*Filter2 + hidden_layer[2]*Filter3 + hidden_layer[3]*Filter4 + hidden_layer[4]*Filter5 + visual_bias 

In [108]:
visual_layer

array([[1.67347652, 2.43001107, 3.20207466],
       [2.19754819, 3.40720131, 2.75708298],
       [2.63364561, 3.88643204, 2.42929587],
       [3.61388869, 2.24825218, 2.15934754],
       [2.09622989, 4.09009489, 2.69082545],
       [2.69842377, 2.40975615, 3.63000807]])

In [109]:
visual_layer_softmax = np.array([softmax(visual_layer[0]), 
                                 softmax(visual_layer[1]), 
                                 softmax(visual_layer[2]), 
                                 softmax(visual_layer[3]), 
                                 softmax(visual_layer[4]), 
                                 softmax(visual_layer[5])])

In [110]:
visual_layer_softmax

array([[0.12915581, 0.2752154 , 0.59562879],
       [0.16387586, 0.5493646 , 0.28675953],
       [0.18813758, 0.65849696, 0.15336546],
       [0.67171543, 0.17143399, 0.15685058],
       [0.0984624 , 0.7230944 , 0.1784432 ],
       [0.23322043, 0.17474302, 0.59203654]])

In [111]:
data[0][data[0]>0] = 1

In [112]:
for i in range(6):
    if data[0][i] == 0:
        visual_layer_softmax[i] *=0

In [113]:
visual_layer_softmax

array([[0.12915581, 0.2752154 , 0.59562879],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.67171543, 0.17143399, 0.15685058],
       [0.0984624 , 0.7230944 , 0.1784432 ],
       [0.23322043, 0.17474302, 0.59203654]])

In [114]:
energy = -(np.sum(np.multiply((visual_layer-visual_bias),visual_layer_softmax)) + np.sum(np.multiply((visual_bias),visual_layer_softmax))+np.sum(np.multiply(hidden_layer,hidden_bias)))
energy

-14.86780026061654

In [115]:
#--------------------------------
#以下開始反向傳播

In [116]:
lr = 0.1

In [117]:
d_h1 = sigmoid(np.sum(U1[0] * Filter1) + hidden_bias[0])
d_h2 = sigmoid(np.sum(U1[1] * Filter2) + hidden_bias[1])
d_h3 = sigmoid(np.sum(U1[2] * Filter3) + hidden_bias[2])
d_h4 = sigmoid(np.sum(U1[3] * Filter4) + hidden_bias[3])
d_h5 = sigmoid(np.sum(U1[4] * Filter5) + hidden_bias[4])

In [118]:
d_h2 = sigmoid(np.sum(U1[1] * Filter2) + hidden_bias[1])
d_h2

0.7118721451770821

In [119]:
d_W1 = lr*(U1*h1 - visual_layer_softmax*d_h1)
d_W2 = lr*(U1*h2 - visual_layer_softmax*d_h2)
d_W3 = lr*(U1*h3 - visual_layer_softmax*d_h3)
d_W4 = lr*(U1*h4 - visual_layer_softmax*d_h4)
d_W5 = lr*(U1*h5 - visual_layer_softmax*d_h5)

In [120]:
Filter1 += d_W1
Filter2 += d_W2
Filter3 += d_W3
Filter4 += d_W4
Filter5 += d_W5

In [121]:
d_softmax = np.abs(visual_layer_softmax - U1) 
d_softmax

array([[0.12915581, 0.2752154 , 0.40437121],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.32828457, 0.17143399, 0.15685058],
       [0.0984624 , 0.2769056 , 0.1784432 ],
       [0.23322043, 0.17474302, 0.40796346]])

In [122]:
d_visual_bias = d_softmax.sum(axis=1)
visual_bias -= lr*d_softmax

In [123]:
d_hidden_bias_1 = np.sum(d_softmax * Filter1) * h1 * (1- h1)
d_hidden_bias_2 = np.sum(d_softmax * Filter2) * h2 * (1- h2)
d_hidden_bias_3 = np.sum(d_softmax * Filter3) * h3 * (1- h3)
d_hidden_bias_4 = np.sum(d_softmax * Filter4) * h4 * (1- h4)
d_hidden_bias_5 = np.sum(d_softmax * Filter5) * h5 * (1- h5)

In [124]:
d_hidden_bias = np.array([d_hidden_bias_1, d_hidden_bias_2, d_hidden_bias_3, d_hidden_bias_4, d_hidden_bias_5])

In [125]:
hidden_bias -= lr*d_hidden_bias

In [130]:
a = np.array([[3,3],[1,2]])
b = np.array([[1,2],[3,5]])
a*b

array([[ 3,  6],
       [ 3, 10]])